name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Build and Upload
      env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}  
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip twine wheel
        python setup.py sdist bdist_wheel
        twine upload dist/* --username __token__ --password "$PYPI_TOKEN"
